on:
  workflow_dispatch:

name: Build-Release[Windows]

jobs:
  build_and_package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python ./script/release_windows_package.py --version 1.0.0
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: oasx-windows
          path: ./oasx_1.0.0_windows.zip
